### ISSUE TITLE
Providing a custom data type to the 'data' property in LineChart

### ISSUE THREAD

**Issue by joshuarichards001** [Abhinandan-Kushwaha/react-native-gifted-charts#149]
Hey,

I'm calling my API which returns an array of objects with the type { price: number, date: string }. Is there a way for me to set the y axis to the price value and the x axis to the date on the value using the LineChart similarly to how Victory Charts has implemented it:

`<VictoryArea
          data={history}
          x="date"
          y="price"
        />`

Cheers,
Josh

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋
X axis labels can be achieved using the `label` property in the data array.

Y axis labels need to be computed using the `maxValue`, `stepValue` and the `noOfSections` props.
They must follow the relation:
```js
maxValue = noOfSections * stepValue;
```
Here's an example-
Considering your data is an array of objects of the type `{ price: number, date: string }`

```js
let dataFromAPI = getDataFromAPI();
let data = dataFromAPI.map(item => return {value:item.value, label:item.date})
let max = Math.max(...dataFromAPI.map(item => item.price))

return(
  <LineChart
      data = {data}
      maxValue = {max}
      noOfSections = {5}
      stepValue = {max/5}/>
)
```

You can consider rounding off the value of the max variable to the nearest 10s or 100s to get more readable values on Y axis.

**Comment by joshuarichards001** [comment]
Ahh, I see, cheers for the solution mate. If you're taking feature requests having that be a built-in functionality like the VictoryArea example I provided would be great!

**Comment by Abhinandan-Kushwaha** [comment]
Hi @joshuarichards001 👋
I agree with you that it would be crispier to have props like `x` and `y` similar to Victory Charts. But I don't find it a compelling feature. Here's why-

It happens that auto computing the x and y axis labels using a properties from data array seems an over-engineering. There's a big possibility of some data missing from the API response. If we try auto-computing the labels in the library, debugging might become more difficult.

Also, it's a one line code to compute labels. So, why not just compute it, instead of depending on the library.

---

The Y axis labels are auto-computed based the max value, there's no need to write any extra code for that.  Props like `yAxisLabelPrefix` and `yAxisLabelSuffix` are also available.

---

For X axis labels, we have the label property in the data array.
Besides, I have added the props `xAxisLabelTexts` and `xAxisLabelTextStyle` in version `1.2.3`🎉 (Thank you @joshuarichards001 for your request)

`xAxisLabelTexts` is an array of Strings, whose length should be equal to the data array's length.
`xAxisLabelTextStyle` is style object which is applied to the X axis label texts.
This makes it a one line code to compute the X axis labels.

Remember, the `label` and `labelTextStyle` properties in the data array are still the first priority. `xAxisLabelTexts` and `xAxisLabelTextStyle` will only have effect for those data points for which we don't have the `label` and `labelTextStyle` properties.
