### ISSUE TITLE
Scroll view disables when pointerConfig prop is enabled

### ISSUE THREAD

**Issue by PROda221** [Abhinandan-Kushwaha/react-native-gifted-charts#154]
Hello, 
I am not able to scroll my graph when I enable pointerConfig prop. 
Scroll view starts working as soon as I disable it. 

package ver:- 1.2.3
react native ver:- 0.66.4

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 👋
Thanks for pointing out the bug. It's now fixed in version `1.2.4`🎉 
Now, to prevent disabling the scroll, just set the property `activatePointersOnLongPress` to true inside the pointerConfig object.

Here's a small explanation for that-

---

If you are using the `pointerConfig` prop, the scroll will be disabled automatically. This is because, it's difficult to achieve both scrolling line and scrolling pointer simultaneously. So if you want to retain the scroll behaviour even after passing the `pointerConfig` prop, then set the property `activatePointersOnLongPress` to true inside the pointerConfig object. This will make the pointers visible only after long press. So, before the long press, user can can scroll the line. Once long pressed, scrolling will be disabled until the release of the long press.

---

The duration after which a press event will be considered as long press can be controlled using the `activatePointersDelay` property inside the pointerConfig object. The default value of `activatePointersDelay` is 150.

**Comment by PROda221** [comment]
That's awesome! Will definitely try this out later. 
Thank you so much! <3
