### ISSUE TITLE
pointerConfig dosent point to data2 

### ISSUE THREAD

**Issue by PROda221** [Abhinandan-Kushwaha/react-native-gifted-charts#155]
When my area graph shows more than 1 data (data1,data2) pointerConfig dosent point towards data2 
it only points to data1

expected behavior:- It should point towards all the data. In my case, data2 values should also be shown.

**Comment by PROda221** [comment]
Hello developers!
any update on this yet?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @PROda221 👋
Thanks for pointing out the bug. It has been fixed in version `1.2.5`🎉

Now, pointers will appear for all data lines by default. If you want to hide pointers for some specific data lines, set the property `hidePointer1`, `hidePointer2`, `hidePointer3` etc to **true** inside `pointerConfig` object.

Also, we can have different colors for different pointers using the property `pointer1Color`, `pointer2Color`, `pointer3Color` etc inside the `pointerConfig` object.

I hope it helps🤗
