### ISSUE TITLE
Dynamic chart data 

### ISSUE THREAD

**Issue by jaikantshikray** [Abhinandan-Kushwaha/react-native-gifted-charts#236]
I have seen the example code and the source code for the library, it only supports 5 items data to be plotted on charts via 5 different data props, is there a way we can plot dynamic data over the chart ?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jaikantshikray 👋
Thanks for requesting the feature. But unfortunately I am running short of time these days. Will definitely work on it once I get some time.

**Comment by tandemloop** [comment]
Hello we urgently require this, can you tell us where to look to do this if you are short on time. Thank you in advance.

**Comment by JoshiAditi1993** [comment]
Hi, we need dynamic data. Is there any workaround for this?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @JoshiAditi1993 @tandemloop @jaikantshikray 👋

This feature is now available in version `1.3.19` onwards. 🎉

Added support for a dynamic number of lines with the help of the `dataSet` prop. We can now pass an array of data instead of using `data`, `data2`, `data3` etc.

See [Line chart props: dataSet](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#dataset--dynamic-number-of-lines)
