### ISSUE TITLE
Multicolor line chart

### ISSUE THREAD

**Issue by aljazkosirnik** [Abhinandan-Kushwaha/react-native-gifted-charts#251]
Hey, I am wondering if it's possible to create a multicolor line chart? Something like this:

![image](https://user-images.githubusercontent.com/32467042/179031610-200fad04-20c5-4af1-9fe8-9d818165f95f.png)

I saw you are limited with your time, I can try to create the PR myself if you can guide me to the right component and quickly describe how you would implement this :)

**Comment by darkholiday** [comment]
I would like to implement the same behavior on my chart aswell
Let me know if you have news.

I can help on the PR

**Comment by Abhinandan-Kushwaha** [comment]
Hi @darkholiday @aljazkosirnik 👋
Thanks for requesting this feature. It is now available in version `1.3.14`🎉

It can be achieved using the some or all of the following props-
```js
lineGradient?: boolean;
lineGradientComponent?: () => any;
lineGradientId?: string;
lineGradientDirection?: string;
lineGradientStartColor?: string;
lineGradientEndColor?: string;
```

Minimal example to show multicolor line chart-

```js
<LineChart
    data={lineData}
    spacing={10}
    hideDataPoints
    lineGradient
/>
```

The output is-

<img width="329" alt="Screenshot 2023-11-02 at 12 29 27 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/7dcc9cc7-2948-4eae-b391-beeeeaa20c05">
<br /><br />
Notice that the line gets a gradient of `lightgreen` and `orange` color by default. These can be customised using the `lineGradientStartColor` and `lineGradientEndColor` props respectively.
<br /><br />
We can use our own gradient component via the `lineGradientComponent` prop. Note that `lineGradient` prop is mandatory when using custom gradient component.
<br /><br />
Here's an example of custom `lineGradientComponent`-

```js
LineChart
  data={lineData}
  spacing={10}
  hideDataPoints
  lineGradient
  lineGradientId="ggrd"
  lineGradientComponent={() => {
    return (
      <LinearGradient id="ggrd" x1="0" y1="0" x2={'0'} y2={'1'}>
        <Stop offset="0" stopColor={'blue'} />
        <Stop offset="0.5" stopColor={'orange'} />
        <Stop offset="1" stopColor={'green'} />
      </LinearGradient>
    );
  }}
/>
```
The output is-

<img width="326" alt="Screenshot 2023-11-02 at 12 36 15 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/f4066888-2426-4d68-940a-c316d4214223">

**Comment by fmmattioni** [comment]
Hi - I guess there is an issue with this feature. When I define my own component, like the example above, the gradient is being done on the range of the data instead of the range of the chart. For example, it does not matter the stop offsets I define, the chart will have all those colors no matter the y-axis value. This distracts from the usefulness of defining my own component, because I wanted to define specific stops for certain y values (which I can calculate like:

offset = y-value / y-axis range

Any ideas?

**Comment by adityaranjan006** [comment]
Can we change the gradient based on values of the data point

**Comment by Abhinandan-Kushwaha** [comment]
@adityaranjan006 can you share an example

**Comment by Abhinandan-Kushwaha** [comment]
Hi @adityaranjan006, if you want the gradient to be applied puerly based on the y Axis values, then you need to add the property `gradientUnits = "userSpaceOnUse"` inside the `<LinearGradient>` tag. Also make sure to x1, y1, x2 and y2 values as `"0%"` or `"100%"` instead of simply giving numerical `'0'` and `'1'`.

Example- 
```js
<LinearGradient id="ggrd" x1="0%" y1="0%" x2="0%" y2="100%" gradientUnits="userSpaceOnUse">
```

Here's a working snack link for the same-
https://snack.expo.dev/@ak_97/lineargradient-based-on-y-axis

**Comment by adityaranjan006** [comment]
> Hi [@adityaranjan006](https://github.com/adityaranjan006), if you want the gradient to be applied puerly based on the y Axis values, then you need to add the property `gradientUnits = "userSpaceOnUse"` inside the `<LinearGradient>` tag. Also make sure to give x1, y1, x2 and y2 values as `"0%"` or `"100%"` instead of simply giving numerical `'0'` and `'1'`.
> 
> Example-
> 
> <LinearGradient id="ggrd" x1="0%" y1="0%" x2="0%" y2="100%" gradientUnits="userSpaceOnUse">
> Here's a working snack link for the same- https://snack.expo.dev/@ak_97/lineargradient-based-on-y-axis

Hi @Abhinandan-Kushwaha, still its sectional or position percentage wise right? if min-max changes same position values will shift in different color position.
