### ISSUE TITLE
LineChart shows tooltip without onPress() on datapoint while scrolling the charts

### ISSUE THREAD

**Issue by ravi123saxena** [Abhinandan-Kushwaha/react-native-gifted-charts#257]
**Describe the bug**
<LineChart 
          data={data}
          thickness={1}
          width={width}
          height={height}
          curved={isBazier}
          pressEnabled
          dataPointsRadius={5}
          showLine
          onPress={(item, index) => {
            onDataPointClick(item)
          }}
        />
**Expected behavior**
should not show alert on scrolling charts

**Screenshots**
showing alert while scrolling chart without onPress() called

 - Device: Android 9
 - Version of the library being used- current version
 React- 18.0
React native- 0.69.1

**Comment by Abhinandan-Kushwaha** [comment]
Hi @ravi123saxena 👋
This issue has now been fixed in version `1.3.2`

`onPress` will now only be called when you press on a data point.  Another prop named `onFocus` has been added.

Here is the list of prop names changed in version `1.3.2`-

| Prop name prior to version `1.3.2` | Prop name in and after `1.3.2`                                 |
| ---------------------------------- | -------------------------------------------------------------- |
| pressEnabled                       | focusEnabled                                                   |
| onPress                            | onFocus (onPress also exists but has diffferent functionality) |
| showDataPointOnPress               | showDataPointOnFocus                                           |
| showStripOnPress                   | showStripOnFocus                                               |
| showTextOnPress                    | showTextOnFocus                                                |

See the complete prop list here- [Line and Area chart props](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md)
