### ISSUE TITLE
line chart support only 5 line datas

### ISSUE THREAD

**Issue by san1109** [Abhinandan-Kushwaha/react-native-gifted-charts#305]
I want to create a graph with package where i need more than 5 data lines but this package supports only 5 line datas. Is there a way to configure this.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @san1109 Currently the library supports only 5 lines in line chart.

**Comment by CHANDRAMOHANnegi** [comment]
Will support for multiple lines be added in future ?
are you working on it ?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @CHANDRAMOHANnegi 
Support for a dynamic number of lines is on my to-do list. I have not started working on it, but it seems like a week's effort.

**Comment by san1109** [comment]
Thanks @Abhinandan-Kushwaha I just edited your package and made it to support 7 lines and stored the edited package in a separate folder. Thanks for the reply.😊

**Comment by Abhinandan-Kushwaha** [comment]
Hi @san1109 @CHANDRAMOHANnegi 👋

Added support for a dynamic number of lines with the help of the `dataSet` prop. We can now pass an array of data instead of using `data`, `data2`, `data3` etc.
This feature is now available in version `1.3.19` onwards. 🎉

See [Line chart props: dataSet](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#dataset--dynamic-number-of-lines)

**Comment by san1109** [comment]
Thanks @Abhinandan-Kushwaha for your valuable effort. This is will now make my work easier.😊

**Comment by Husk3r000** [comment]
Hi @Abhinandan-Kushwaha 

I'm currently trying to use multiple line datasets in the BarChart component, but it seems that it only supports two lines: lineData and lineData2. For my use case, I need to display more than two lines over the bar chart.

It would be really helpful for data visualization use cases that require more than two comparative lines.

Thanks again for your hard work!

**Comment by Sanji-1109** [comment]
Sorry for the delayed response @Husk3r000 , I am not using this chart anymore but last time I saw it, it had 5 line data support

**Comment by Sanji-1109** [comment]
Hi @Husk3r000 I would modify the package in the node modules according to my need if I am too lazy to find another package that supports my requirement. 😊. I am glad to tell you what to change in the package but I would strongly recommend you to find another package because modifying node modules would make you to keep the package as a seperate folder and push it in repo too which may cause a size issue in your file

**Comment by Husk3r000** [comment]
Hello @Sanji-1109  I really appreciate you taking the time to answer my question. Could you please help me make the changes in the node modules? I can’t find the new package, and I’ve already built my entire functionality with the current one, so switching to another package would take much more time. It would be a great help if you could tell me how to modify it in the node modules according to my needs.

**Query**
I just want to display more than 2 lines in the BarChart. Currently, it only supports lineData and lineData2, but I’d like to show at least 5 lines. Thanks!

**Comment by Husk3r000** [comment]
@Sanji-1109 I really appreciate your time and effort. I’m waiting for your response.
