### ISSUE TITLE
Can you customize the point points horizontally?

### ISSUE THREAD

**Issue by HarryHMinh** [Abhinandan-Kushwaha/react-native-gifted-charts#320]
I have a problem, and I am looking for a way but it's better if I can help.

As shown, I want to customize the point points horizontally.

**Comment by iujisato** [comment]
I'm looking to do something like that too, is there an option to set the reference line to be the last value? 
I've seen that in a barChart there's an props called showLine, maybe that can be a good reference point...
I was also thinking that maybe we can do something like a horizontalStrip for the line/area graph

**Comment by Abhinandan-Kushwaha** [comment]
Hi @iujisato 👋
If you want to show a reference line across the last value, you can use the below props-

```js
showReferenceLine1
referenceLine1Position={data[data.length-1].value}
```

If you want to show the reference line across the max value, then-

```js
showReferenceLine1
referenceLine1Position={Math.max(...data.map(i => i.value))}
```

If you want a horizontal strip instead of reference line, you can set the thickness of the reference line to any custom value, for example-

```js
referenceLine1Config={{
  type: 'solid',
  thickness: 10,
}}
```

Here's an example that shows reference line across the max value-
```js
<LineChart
  data={data}
  hideRules
  showReferenceLine1
  referenceLine1Position={Math.max(...datad.map(i => i.value))}
/>
```

The output is-

<img width="318" alt="line" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/c192a51d-8014-4bb6-9ada-a17ec9134cdf">

To render a horizontal strip, instead of a reference line, I added

```js
referenceLine1Config={{
  type: 'solid',
  thickness: 10,
}}
```
Now the chart becomes like this-

<img width="321" alt="strip" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/3cd03c46-0f30-42cd-9082-fe40ca41f61c">


I hope it helps. 🙂
