### ISSUE TITLE
dataPointText out of the chart when "value" equals "maxValue"

### ISSUE THREAD

**Issue by VitorGabrieldeOliveira** [Abhinandan-Kushwaha/react-native-gifted-charts#339]
**Describe the bug**
Hi! I have an area chart and I need to display `dataPoints` and `dataPointText` on each one.
The Y axis has a `minValue={0}` and `maxValue={100}` and when I pass an object to the `data` prop containing `value: 100`, which is the same of `maxValue`, the `dataPointText` is outside of the chart as you can see on the first screenshot.

**To Reproduce**
```
import React from 'react';
import { useWindowDimensions } from 'react-native';

import { LineChart } from 'react-native-gifted-charts';

export function AreaChart() {
  const windowDimensions = useWindowDimensions();

  return (
    <LineChart
      areaChart
      curved
      data={[
        { value: 50, dataPointText: '50%', label: '01/07' },
        { value: 63, dataPointText: '63%', label: '02/07' },
        { value: 61, dataPointText: '61%', label: '04/07' },
        { value: 67, dataPointText: '67%', label: '05/07' },
        { value: 70, dataPointText: '70%', label: '06/07' },
        { value: 100, dataPointText: '100%', label: '09/07' },
        { value: 74, dataPointText: '74%', label: '10/07' }
      ]}
      height={200}
      initialSpacing={32}
      spacing={80}
      thickness={2}
      minValue={0}
      maxValue={100}
      stepValue={20}
      yAxisLabelSuffix="%"
      dashGap={8}
      dashWidth={8}
      noOfSections={5}
      color="#27BF5A"
      dataPointsColor="#27BF5A"
      dataPointsHeight={20}
      startFillColor="#27BF5A"
      startOpacity={0.45}
      endFillColor="#27BF5A"
      endOpacity={0}
      scrollToEnd
      xAxisLabelTextStyle={{ color: '#545454', fontSize: 12, textAlign: 'center', marginBottom: 8 }}
      yAxisTextStyle={{ color: '#545454', fontSize: 12 }}
      textShiftY={-4}
      textShiftX={-10}
      textColor="#27BF5A"
      textFontSize={12}
      xAxisLength={windowDimensions.width}
      rulesColor="#F4F4F4"
      yAxisColor="#FFFFFF"
      hideOrigin
      xAxisColor="#C6C6C6"
    />
  );
}
```

**Expected behavior**
I expect to see `dataPointText` when `value` equals `maxValue`.

**Screenshots**
![image](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/44534745/93efe5fe-e27a-4d84-b8e2-67a7815fa596)

 - Device: iPhone 14
 - OS: iOS 16.4
 - Version of the library being used: ^1.3.2

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VitorGabrieldeOliveira 👋
Thanks for pointing this out. We should be able to add extra height to the chart to accommodate the `dataPointText` displayed above the max data point. Unfortunately, this is not supported as of now. I will add this feature in the next release.

I can suggest you a workaround-

Let's add some extra space at the top of the chart by adding one more section in the y Axis (above 100%)
We can have `noOfSections={6}` instead of 5. But this will force us to set `maxValue={120}`.
Here is the chart after making this change-

<img width="309" alt="areaWithLabel" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/b6145a89-6c95-4a72-86dd-4a9667354f84">

But this adds 120% at the y Axis. I assume this is not desired. The `120%` thing is annoying.
We can get rid of this by using `yAxisLabelTexts` and passing whitespace as the 6th label. So the final code should be-

```js
<LineChart
      areaChart
      curved
      data={[
        { value: 50, dataPointText: '50%', label: '01/07' },
        { value: 63, dataPointText: '63%', label: '02/07' },
        { value: 61, dataPointText: '61%', label: '04/07' },
        { value: 67, dataPointText: '67%', label: '05/07' },
        { value: 70, dataPointText: '70%', label: '06/07' },
        { value: 100, dataPointText: '100%', label: '09/07' },
        { value: 74, dataPointText: '74%', label: '10/07' }
      ]}
      height={200}
      initialSpacing={32}
      spacing={80}
      thickness={2}
      minValue={0}
      maxValue={120}
      stepValue={20}
      yAxisLabelTexts={["","20%","40%","60%","80%","100%"," "]}
      dashGap={8}
      dashWidth={8}
      noOfSections={6}
      color="#27BF5A"
      dataPointsColor="#27BF5A"
      dataPointsHeight={20}
      startFillColor="#27BF5A"
      startOpacity={0.45}
      endFillColor="#27BF5A"
      endOpacity={0}
      scrollToEnd
      xAxisLabelTextStyle={{ color: '#545454', fontSize: 12, textAlign: 'center', marginBottom: 8 }}
      yAxisTextStyle={{ color: '#545454', fontSize: 12 }}
      textShiftY={-4}
      textShiftX={-10}
      textColor="#27BF5A"
      textFontSize={12}
      xAxisLength={windowDimensions.width}
      rulesColor="#F4F4F4"
      yAxisColor="#FFFFFF"
      hideOrigin
      xAxisColor="#C6C6C6"
    />
```
Notice that `yAxisLabelSuffix` is no longer needed.

The output of the above code is-

<img width="305" alt="Screenshot 2023-07-11 at 11 35 39 PM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/35bb6415-d639-4768-9d96-cfda242f3dd9">

I hope it helps. 🙂

**Comment by VitorGabrieldeOliveira** [comment]
Thank you very much for replying @Abhinandan-Kushwaha :D
I'll follow your suggestion and will be following the next releases.
