### ISSUE TITLE
How to get all the values Line chart is going to show in Y-axis

### ISSUE THREAD

**Issue by jatins52** [Abhinandan-Kushwaha/react-native-gifted-charts#382]
Hello @Abhinandan-Kushwaha,

Thank you for this great library. 

I have one question:
values in my component are very large so we have to show them in billions, millions and thousands according to how large it is.
like $3445M, or $134K etc.
What I am currently doing is that I am showing three custom values in Y-axis using "yAxisLabelTexts", with below logic:
number of steps : 2
values: 0, minValue, maxValue (minValue and maxValue are taken from data array)

my client does not want to show 0 in Y-axis, for which I tried to use "yAxisOffset" prop, but when I use it values are different and I am not understanding how to format them.
Is there a way to get values from chart component which it is going to show on Y-axis?

Current data on Y-axis:
[1445490094, 1651988679, 1858487264, 2064985849, 2271484434, 2477983019, 2684481604, 2890980189]
minValue = 1445490094
maxValue = 2890980189

Y-axis labels when "yAxisOffset" prop is not used:
Y-axis values shown by line chart: [0, 1445490095, 2890980190]
yAxisLabelTexts = ['0', '$1,446M', '$2,891M'] 

Y-axis labels when "yAxisOffset" prop is used:
yAxisOffset : 144549009.4 (10% of minValue)
Y-axis values shown by line chart: [144549009.4, 1517764599.4, 2890980189.4]
How do I get above values for 'yAxisLabelTexts'.

Sorry for long questions.
Thanx in advance :)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jatins52 👋
Thanks for bringing this up. I have fixed the issue. Please update to version `1.3.6` of react-native-gifted-charts. 

In your example, there is no relevance of the `minValue` prop. `minValue` represented the most negative value on the Y axis. To kill all confusion `minValue` is now renamed to `mostNegativeValue`

Coming to your issue, if I understand correctly, these are your requirements-

1. You don’t want to show 0 on the Y axis, so you can use the `yAxisOffset` prop
2. You want to show formatted labels on the Y axis, so you can use `yAxisLabelTexts` prop. Make sure that the first string in the `yAxisLabelTexts` array represents the yAxisOffset value.

If your problem is still not, please send the exact code, I will debug.
