### ISSUE TITLE
Why is only 5 lines of maximum allowed in line chart?

### ISSUE THREAD

**Issue by sahad00** [Abhinandan-Kushwaha/react-native-gifted-charts#431]
I have an use case wherein the number of lines depends based on the user preference , why is it specifically limited to 5 lines with data data2 data3 ... and so ... data5, is their any other solution for the lineChart to draw more than 5 lines

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sahad00 
I am currently working on enabling dynamic number of lines. It should be completed by this week.

**Comment by sahad00** [comment]
@Abhinandan-Kushwaha  hi thank u so much I am highly expecting it

**Comment by Abhinandan-Kushwaha** [comment]
Hi @sahad00 👋
This feature is now available in version `1.3.19` onwards.

Added support for a dynamic number of lines with the help of the `dataSet` prop. We can now pass an array of data instead of using `data`, `data2`, `data3` etc.

See [Line chart props: dataSet](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/LineChart/LineChartProps.md#dataset--dynamic-number-of-lines)
