### ISSUE TITLE
both dotted and dashed lines at the same line chart

### ISSUE THREAD

**Issue by Rinku222** [Abhinandan-Kushwaha/react-native-gifted-charts#432]
I have a requirement where i wanna show dashed and dotted line both partially in line chart. like from x-axis from 1 to 2 and to 3 i want straight solid line and dotted for 5 to 6 to 7 and again solid line from 7 to 8 to 9.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Rinku222 
Thanks for requesting this feature. I will add it by this weekend.

**Comment by Rinku222** [comment]
great thank you. Looking forward for this feature.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Rinku222 👋
This feature is now available in version `1.3.17`🎉

We now have a prop named `rulesConfigArray` which can be used to customise the properties (like color, type etc) of specific rules. In other words, we can now customise each rule separately.

Here's an example. Let's say we have an ordinary Bar chart which has 10 rules rendered by default. We want to make the 8th rule **Red** and the 9th rule **Solid** as shown below-

<img width="242" alt="rulesConfigArray" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/e73affe8-eeae-4187-98de-253440252b79">

The code for the above chart is-
```js
<BarChart
  data={[
    {value: 5}, {value: 8}, {value: 7}, {value: 4}
  ]}
  rulesConfigArray={
    [ , , , , , , , , {rulesColor: 'red'}, {rulesType: ruleTypes.SOLID}]
  }
/>
```

Notice that we have passed the values to 8th and 9th items of the `rulesConfigArray` array and the counting started from X-axis upwards.

**Comment by Rinku222** [comment]
@Abhinandan-Kushwaha i want something like this
![Group 23 (1)](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/62506478/6b18e30d-3f60-44b3-be35-e892b6690bdc)
where i can manage line straight or dotted between two points in **line chart**.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @Rinku222 👋
Thanks for this unique requirement. This is now available in version `1.3.18` 🎉

It can be achieved using the `lineSegments` prop. `lineSegments` is an array of objects used to customize segments (parts) of line.

Below is an example-
```js
<LineChart
  data={[{value: 5}, {value: 8}, {value: 7}, {value: 4}, {value: 6}]}
  lineSegments={[
    {startIndex: 0, endIndex: 1, color: 'red'},
    {startIndex: 1, endIndex: 2, color: 'green', strokeDashArray: [4, 1]},
    {startIndex: 2, endIndex: 3, color: 'orange'},
  ]}
/>
```

The output of the above code is-

<img width="272" alt="Screenshot 2023-11-21 at 5 43 35 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/b09d2da1-21ff-4370-8546-c29671f8208a">

Note that the `startIndex` and `endIndex` properties are mandatory in each object of the `lineSegments` array.

```js
type LineSegment = {
  startIndex: number, // required
  endIndex: number, // required
  color?: string | ColorValue,
  thickness?: number,
  strokeDashArray?: Array<number>,
};
```
Similarly you can make the 2nd, 3rd, 4th and 5th lines segmented using the `lineSegments2`, `lineSegments3`... props.

**Comment by csmartinsfct** [comment]
@Abhinandan-Kushwaha I don't know if its worth opening a new issue for this one. I have a requirement to draw the line in a different colour depending on the selectedIndex (passed to `pointerLabelComponent`). So the idea is that the full line is ex: black and if `pointerLabelComponent` gets called then the line after that index should change to be green instead. I can't really make it work with `lineSegments` due to re-renders it seems. The idea is to make the line a different colour past the point the user is dragging essentially. Let me know if that makes sense and if you already know how this may be achieved using the current API.

Here is an image for reference:

<img width="744" alt="Screenshot 2024-09-26 at 00 09 15" src="https://github.com/user-attachments/assets/659f888e-9605-40fa-9931-0227cca8fca4">

Thanks a lot!

**Comment by biapar** [comment]
But the index is by x range value and not by Y value?
