### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by christophby** [Abhinandan-Kushwaha/react-native-gifted-charts#473]
**Describe the bug**
> Found 187 errors in 22 files.

If you run `yarn tsc` you'll get 187 typescript errors in this project.
Most of them are
`Parameter 'xyz' implicitly has an 'any' type.`

**To Reproduce**
1. Add a `tsconfig.json` in the root with `{"extends": "@tsconfig/react-native/tsconfig.json"}` 
2. Add `@tsconfig/react-native` to the dev dependencies (is a default in react native typescript projects)
3. Run typecheck `yarn tsc` or `npm run tsc` 
4. See errors

**Expected behavior**
There shouldn't be any errors.

**Comment by 1kDustin** [comment]
@christophby whats the best way to get around this temporarily?

**Comment by christophby** [comment]
@1kDustin I'm using patch-package to put a `//@ts-nocheck` on top of (almost) each file

**Comment by digitalthjarta** [comment]
First time trying out gifted charts. Are these errors new in the latest version, or have they always been there? Is it worse using an older version? 

Since I'm not yet invested in this particular package, it just look nice for what I want, I don't really want to do some hacks of adding 'nocheck' to a bunch of files. 

Any chance this will be fixed soon?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @digitalthjarta 
These typescript errors have always been there. I'll try to fix them in coming 1 or 2 weeks.

**Comment by digitalthjarta** [comment]
Thank you!

**Comment by christophby** [comment]
Nice @Abhinandan-Kushwaha

**Comment by jasonleibowitz** [comment]
One temporary fix, that is not ideal, is to add the [noimplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny) option to your tsconfig:

```
"compilerOptions": {
    "noImplicitAny": false,
    ...
  },
```

To enforce _some_ of the rules enforced by that config option, you can utilize [this typscript-eslint rule](https://typescript-eslint.io/rules/typedef/#parameter). Note that their docs say to prefer `noImplicitAny` over this rule. Hopefully when types for this package are fixed, we can revert this rule.

**Comment by bryanltobing** [comment]
what is the best way to workaround this?

**Comment by dogancancelik12** [comment]
Any updates here? We can not get a build with tsc build

**Comment by araphiel-nf** [comment]
This repo [exports direct typescript code](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/package.json#L5) without bundling it, all typescript errors from this package (and `gifted-core`) will be reported in your downstream user's projects.

Regardless of a user's tsconfig settings, these errors prevent teams from building or checking types on their own code.

This can be fixed if you decide on either:

- Compile and bundle this package into JS
   - Pull Request: #559 
- Or keep serving pure typescript and fix types on this repo & `react-gifted-core`
  - PR for `react-gifted-core`: https://github.com/Abhinandan-Kushwaha/gifted-charts-core/pull/5

**Comment by tfsjohan** [comment]
> Hi @digitalthjarta These typescript errors have always been there. I'll try to fix them in coming 1 or 2 weeks.

Any updates to this? 
Starting to feel like "Elon Musk two weeks" now. :) 

Painful to see all github actions fail because of the missing types from this package.

**Comment by araphiel** [comment]
Here's a workaround for this issue: https://gist.github.com/araphiel/b3d13ade7f9fe69e99c3d053196557d2

Hope this can help 👋

**Comment by christophby** [comment]
Any updates on this @Abhinandan-Kushwaha ? :)

**Comment by cjmling** [comment]
It seems expo eas build failed because of this type error.

// Saying this because `npx tsc --noEmit` throw error on this library. Removing all the charts from the app , then build again did pass.

**Comment by rodnoycry** [comment]
> Here's a workaround for this issue: https://gist.github.com/araphiel/b3d13ade7f9fe69e99c3d053196557d2
> 
> Hope this can help 👋

Windows 10 - I got some troubles running command to update every file from this guide, so I used this command in my **cmd** in order to add `// @ts-nocheck` line to every file:

1. First I navigated to the module folder from project root:
```sh
cd ./node_modules/react-native-gifted-charts/src
```
2. Then I ran this command to add `// @ts-nocheck` line to every file:
```sh
for /R %i in (*.ts *.tsx) do (echo // @ts-nocheck > temp & type %i >> temp & move /Y temp %i)
```

3. After that I ran patch-package for updated module from my project root
```sh
npx patch-package react-native-gifted-charts
```

**Comment by kuldip-simform** [comment]
Any updates on this ?

**Comment by Abhinandan-Kushwaha** [comment]
Hi @christophby @1kDustin @digitalthjarta @jasonleibowitz @bryanltobing @dogancancelik12 @araphiel @tfsjohan @cjmling @rodnoycry @kuldip-simform 👋

`react-native-gifted-charts` is now shipping compiled js files instead of ts files from version `1.4.22` onwards. This should fix all type related issues. 🎉
