### ISSUE TITLE
X Labels not showing on Android

### ISSUE THREAD

**Issue by fodeguirassy** [Abhinandan-Kushwaha/react-native-gifted-charts#496]
**Describe the bug**
X labels are showing on iOS but not for Android

**Screenshots**

![File (1)](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16901741/e29f867c-049e-4b3f-a365-e8e913ff6ba8)

![capture](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16901741/80ed1c62-3260-47b9-a5bd-aa9542165bfa)

- RN version : 0.61.5
-  react-native gifted-chart : ^1.3.24

**Additional context**
https://gist.github.com/fodeguirassy/e4dd32163bddf7a8c17a460811cc6671

**Comment by Abhinandan-Kushwaha** [comment]
Hi @fodeguirassy 
Can you please install the latest version of `react-native-gifted-charts` (1.3.30)

**Comment by fodeguirassy** [comment]
Hi @Abhinandan-Kushwaha 

Thanks for your quick answer. 
Updating to `1.3.30` didn't help. 

I applied the `xAxisLabelsHeight`, labels are visible but a strange bottom margin

![Screenshot 2024-01-12 at 08 52 04](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16901741/5f6948c3-e074-4151-8291-d397187329e0)

![capture](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/16901741/7eb26322-ae76-48d4-94fb-d7506ab167f6)

**Comment by Abhinandan-Kushwaha** [comment]
Hi @fodeguirassy 👋
The labels are shifted upwards due to the `xAxisLabelsHeight` prop. You can use the `xAxisLabelsVerticalShift` prop to adjust the vertical position of the X-axis labels.

Please take a look at [the docs](https://gifted-charts.web.app/barchart)

<img width="667" alt="xLabels" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/ccd04c82-0b9e-4ee4-ad13-3f8d8ae4db3f">

Related issue- https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/433

**Comment by Jeijie** [comment]
hi, i had same issue,and i had tried xAxisLabelsHeight，xAxisLabelsVerticalShift props to  customize the X axis labels。But when I adjust the position below the x-axis, the label will be cropped and covered. What should I do？
<img width="313" alt="test" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/9338052/a7d8dccc-4b51-4a54-a723-e8e1e78adea0">
