### ISSUE TITLE
labels overflow

### ISSUE THREAD

**Issue by leonardo409188** [Abhinandan-Kushwaha/react-native-gifted-charts#653]
How can I resolve this overflow issue? I tried a custom label but it did not work

<img width="351" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/73248873/adad1828-ac38-45f1-93e5-67f94fcfa68f">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @leonardo409188 👋

You can shift the x-axis labels of the first and the last data item by adding margins inside the `labelTextStyle` property as shown below-

```ts
const App = () => {
  const stepsData: lineDataItem[] = [
    {
      label: '21/06',
      labelTextStyle: {marginLeft: 30}, // add marginLeft to the 1st data item
      value: 0,
    },
    {
      value: 62,
    },
    {
      label: '03/07',
      labelTextStyle: {marginRight: 10}, // add marginRight to the last data item
      value: 0,
    },
  ];

  return (
    <LineChart
      height={160}
      width={324}
      curved
      areaChart
      data={stepsData}
      initialSpacing={0}
      endSpacing={0}
      spacing={160}
    />
  );
}
```

Output-

<img width="356" alt="Screenshot 2024-06-18 at 3 12 46 AM" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/20596944/a866215a-ea21-427a-b8ed-88b73efe5142">

**Comment by McFly78** [comment]
I had the same issue when the initialSpacing value is lower than de default value (20).
I solved it by adding:
const initialSpacing=0 // value of the initialSpacing props
labelTextStyle:{marginLeft: (20 - initialSpacing)} //20 is the default initial spacing
<LineChart 
    data={arrayValues.map((v, index) => {
     let point= {
        value: v, 
        label: index, 
        **labelTextStyle:{marginRight: -(20 - initialSpacing)}**
        }
        return (point)
        }
    )}
   
    **initialSpacing= {initialSpacing}**
    ....
/>

However, if you have a lot of values on the graph, the width of the labels is very small and adding a left margin will make the text labels disappear because there is no space left.
So instead of adding a marginLeft, I added a negative marginRight.
**labelTextStyle:{marginRight: -(20 - initialSpacing)}**

For me it works for all screen sizes (iPhone, iPad, ...)
