### ISSUE TITLE
 yAxisLabelTexts we must specify the value 

### ISSUE THREAD

**Issue by VijinR** [Abhinandan-Kushwaha/react-native-gifted-charts#67]
@Abhinandan-Kushwaha by using yAxisLabelTexts we must specify the value also right?how we will get the y-axis value been generated by default by library?I need the default yaxis value generated by library with '£' appended at beginning

_Originally posted by @VijinR in https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/60#issuecomment-1011785061_

**Comment by Abhinandan-Kushwaha** [comment]
Hi @VijinR 👋
I have added the props `yAxisLabelPrefix` and `yAxisLabelSuffix` in the version `0.2.9`. With these props, you can generate default values for the y-axis labels. These props can be passed directly to the `<BarChart/>` and `<LineChart/>` components.

I appreciate your consistent efforts in making this library better by figuring out various issues and suggesting edits.👏

**Comment by NemyaNation** [comment]
@Abhinandan-Kushwaha 

Documentation states you can set `yAxisLabelText` as data point for y-axis data point, however this does not work.

Checking the code, there is no mention of this field anywhere: 

https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/b3c05d961bd91dbbdb8f2c8470f92d1eed1ac46b/src/LineChart/index.tsx#L255

---

I need this because when using `yAxisLabelTexts` you have to pick your labels very carefully to make sure they match the graph boundaries and I don't want to handle this myself.

I would much rather prefer to set the y-label for each data point and let your library do the existing heavy lifting.
