### ISSUE TITLE
Add Y-Axis label above the bar in bar chart

### ISSUE THREAD

**Issue by verofy-simon-denny** [Abhinandan-Kushwaha/react-native-gifted-charts#68]
Hi, I just wondered if it was possible to add the value above each bar in the bar chart? I can see it on the screenshots etc, but there isn't documentation for this feature.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @verofy-simon-denny 👋
In order to add a label **above** the bar, you can use the `topLabelComponent` property in the objects of the data array.

Here's an example-

```js
<BarChart
data={[
  {
    value: 70,
    label: 'Jan',
    topLabelComponent: () => {
      return <Text>70</Text>;
    },
  },
  {
    value: 90,
    label: 'Feb',
    topLabelComponent: () => {
      return <Text>90</Text>;
    },
  },
  {
    value: 120,
    label: 'Mar',
    topLabelComponent: () => {
      return <Text>120</Text>;
    },
  },
}]
/>
```
Additional prop -> There's a prop named `topLabelContainerStyle` to provide styling to the wrapper component around the topLabelComponent.

Hope it helps 🤗
