### ISSUE TITLE
Auto center tooltip

### ISSUE THREAD

**Issue by carlosriveroib** [Abhinandan-Kushwaha/react-native-gifted-charts#713]
Hi @Abhinandan-Kushwaha, is it possible to autocenter the tooltip? I can see tooltip position is left at the same point with the left of its bar. Could be tooltip positioned to the center?

<img width="453" alt="Captura de pantalla 2024-07-18 a las 1 10 38" src="https://github.com/user-attachments/assets/7f334fe6-baa4-41f2-8f23-8d5aa7941b52">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @carlosriveroib 
Thanks for suggesting this feature. I will try to implement it in the next release.

Meanwhile, you can manually adjust the tooltip to center by giving a _negative marginLeft_.

**Comment by Abhinandan-Kushwaha** [comment]
Hi @carlosriveroib 
I have added a new prop named `autoCenterTooltip`. It is available in versions `1.4.17` onwards.

**Comment by carlosriveroib** [comment]
Wow, what a beast

One suggestion, when I was looking for charts libraries for my project, I took a look at this one and the feeling was that it was either not maintained or not very good. The look & field of the docs page seems like "old". For example, in Github, there are no releases created. Then I tried another chart library and it wasn't what I was looking for, so I ended up giving this one a try and OMG it's the best charts library I've tried. The doc is the best with lots and lots of examples. I don't understand how this library can only have 661 stars because it is wonderful. I really appreciate your work. Thank you

**Comment by carlosriveroib** [comment]
Do you want help creating a new docs web using NextJS and this template? https://nextra.site/

**Comment by Abhinandan-Kushwaha** [comment]
@carlosriveroib Of course!!
I would love to have the docs revamped. Any help is greatly appreciated.
I will make the current docs open source. You can see the code and we can together make a new open source repos with the template you suggested.

In fact, I am planning to include auto-code/codegen where developers can make charts using drag and drop and it will generate the code. This is now possible because I have recently released the web version of the library - [react-gifted-charts](https://www.npmjs.com/package/react-gifted-charts)

We can connect over Meet/Zoom when you are available. I am mostly available on the weekends.

**Comment by carlosriveroib** [comment]
Perfect, let's meet this weekend. Send me meet invitation to criveroib@gmail.com, add me to discord if you want carlosriveroib#6748 or we can chat in another app

**Comment by Abhinandan-Kushwaha** [comment]
Hi @carlosriveroib 
Let's connect when you're available- 
react-native-gifted-charts docs
July 28, 2024, 5:00pm – July 29, 2024, 12:00am · 
Time zone: Asia/Kolkata
Google Meet joining info
Video call link: https://meet.google.com/hjk-mmqb-ypk

**Comment by carlosriveroib** [comment]
Can you meet at 20:30 Asia/Kolkata timezone?

**Comment by Abhinandan-Kushwaha** [comment]
Sure @carlosriveroib
