### ISSUE TITLE
Horizontal Bar Chart does not properly fit parent container width and leaves empty space at the top

### ISSUE THREAD

**Issue by buildtheui** [Abhinandan-Kushwaha/react-native-gifted-charts#726]
This is the continuation of the not solved closed issue #647 

The proposed solution does not solve the problem, actually this was my first approach and it has the follow problems:

1. you've got to statically define the container height. This does not happen with vertical BarCharts, as they take up the available parent component height.
2. If we follow your recommendation the empty space now is at the top of the element. as shown on the following image
<img width="400" alt="Screenshot 2024-07-22 at 6 28 11 PM" src="https://github.com/user-attachments/assets/e2a4659a-00ff-4157-bc7a-d02a8bd661ce">

Part of the empty space mention in number 2, it's because I need to increase the xAxisLabelsVerticalShift, so labels don't overlap the horizontal bars, and for some reason whenever I increase this number the top empty space increases too.

BTW thanks for creating and maintaining this library

**Comment by Abhinandan-Kushwaha** [comment]
Hi @buildtheui 👋

Horizontal bar charts are obtained by rotating normal bar charts. That's why the height of the chart is not working as expected. You will have to find a workaround to adjust the chart and its neighbour Views.

The documentation says that horizontal charts are still in `beta`.

<img width="498" alt="Screenshot 2024-07-26 at 1 24 39 AM" src="https://github.com/user-attachments/assets/afedb409-1c38-41fa-89f0-6d972dc4f546">

The documentation also says-

> Developers should first render the chart as a normal chart, add all the props, and then make it horizontal at the end.

I will try to fix this issue of height adjustment soon. In fact, I might have to redesign the horizontal charts form scratch instead of rotating the normal bar charts. But it will take time.
Till then try workarounds to adjust the chart and its neighbour Views.
