### ISSUE TITLE
We can't change the label style

### ISSUE THREAD

**Issue by zahinafsar** [Abhinandan-Kushwaha/react-native-gifted-charts#82]

**Comment by Abhinandan-Kushwaha** [comment]
Hi @zahinafsar 👋

**For styling the Y-Axis labels** we can use the `yAxisTextStyle` prop.

**For X-Axis labels** -
We can give our own custom label component to the entries of the data array using the labelComponent property.

Since it is a custom component, you can give it any styling of your choice.
